//Created by Action Script Viewer - http://www.buraks.com/asv
package {
    import flash.display.*;

    public class GameConfigData {

        public static const CsbRankConfig:String = "Resources/GameData/CsbRank.xml";
        public static const HelpConfig:String = "Resources/GameData/HelpConfig.xml";
        public static const GameFrameRate:int = 30;
        public static const TreasureList:String = "Resources/GameData/TreasureList.xml";
        public static const EquipSucessSwf:String = "Resources/Effect/Sucess.swf";
        public static const GameSkillBuffList:String = "Resources/GameData/GameSkillBuff.xml";
        public static const GuildSkillsList:String = "Resources/GameData/GUILDSKILLSInfo.xml";
        public static const TowerRewardList:String = "Resources/GameData/TRIAL_AWARDInfo.xml";
        public static const ExpList:String = "Resources/GameData/Exp.xml";
        public static const ModelOffsetNpcEnemy:String = "Resources/GameData/ModelOffsetNPC.xml";
        public static const TargetConfig:String = "Resources/GameData/rookie_target.xml";
        public static const EquipFailSwf:String = "Resources/Effect/Fail.swf";
        public static const MapConfigsPath:String = "Scene/Configs.xml";
        public static const PetExpList:String = "Resources/GameData/PetExp.xml";
        public static const AchieveList:String = "Resources/GameData/AchieveList.xml";
        public static const TowerInfoList:String = "Resources/GameData/TOWER_BARRIER_INFOSInfo.xml";
        public static const UILibrarySelectRole:String = "Resources/GameDLC/UILibrary_SelectRole.swf?v=1";
        public static const ModelOffsetMount:String = "Resources/GameData/ModelOffsetMount.xml";
        public static const PetRaceActionList:String = "Resources/GameData/PET_FIGHT_ACTIONS.xml";
        public static const BigMapSwf:String = "Resources/bigmap.swf";
        public static const GuideTreasureAssetsSwf:String = "Resources/GuideTreasureAssets.swf";
        public static const OccupationIntroXML:String = "Resources/GameData/OccupationIntroList.xml";
        public static const GameSkillList:String = "Resources/GameData/NEWSKILLSInfo.bml";
        public static const GameSkillListSWF:String = "Resources/GameSkill/";
        public static const EquipRefine:String = "Resources/GameData/EquipRefine.xml";
        public static const NOTICE_DATA:String = "Resources/Notice.swf?v=2.0";
        public static const ItemProtoList:String = "Resources/GameData/CITEMInfo.bml";
        public static const PetRaceLoseSwf:String = "Resources/Effect/RaceLose.swf";
        public static const PetStrengthenSwf:String = "Resources/Effect/PetStrengthen.swf";
        public static const ChallengedFailSwf:String = "Resources/Effect/ChallengedFail.swf";
        public static const FaceSwf:String = "Resources/face.swf";
        public static const SoundLibrary:String = "Resources/audio.swf";
        public static const TaskPathRandom:String = "Resources/GameData/TaskPathRandom.xml";
        public static const MoveToSwf:String = "Resources/MoveTo.swf";
        public static const ActivityEveryDay:String = "Resources/GameData/GameEveryDay.xml";
        public static const ChallengedSuccessSwf:String = "Resources/Effect/ChallengedSuccess.swf";
        public static const PetRaceFightSwf:String = "Resources/GameSkill/1H.swf";
        public static const LevelUpSwf:String = "Resources/LevelUp.swf";
        public static const QuestInfoAfter60:String = "Resources/GameData/CQUESTInfo100.bml";
        public static const TitleDefList:String = "Resources/GameData/TitleDefList.xml";
        public static const RewardChest:String = "Resources/Effect/RewardChest.swf";
        public static const ModelOffsetPlayer:String = "Resources/GameData/ModelOffsetPlayer.xml";
        public static const MapTree:String = "Resources/GameData/MapTree.xml";
        public static const PetRaceRewardList:String = "Resources/GameData/PetRace_RewardInfo.xml";
        public static const AutoList:String = "Resources/GameData/AUTOMATISMInfo.bml";
        public static const CsbRewardItemList:String = "Resources/GameData/CR_BATTLE_BONUS_INFOInfo.xml";
        public static const CoordinatesEquip:String = "Resources/GameData/CoordinatesEquip.xml";
        public static const GameCommonAudio:String = "Resources/GameMusic/common/";
        public static const GameEffectSWF:String = "Resources/Effect/";
        public static const TransformEffectSwf:String = "Resources/Effect/TransformEffect.swf";
        public static const QuestInfoList:String = "Resources/GameData/CQUESTInfo50.bml";
        public static const ActivityConfig:String = "Resources/GameData/ActivityConfig.xml";
        public static const GuideConsignmentAssetsSwf:String = "Resources/GuideConsignmentAssets.swf";
        public static const FireEffectSwf:String = "Resources/Effect/FireEffect.swf";
        public static const TransferSceneSwf:String = "Resources/TransferScene_1.swf";
        public static const UILibraryCreateRoleSimple:String = "Resources/GameDLC/UILibrary_CreateRole_Simple.swf";
        public static const RandomNameDic:String = "Resources/GameData/RandomName.xml";
        public static const PetRaceWinSwf:String = "Resources/Effect/RaceWin.swf";
        public static const LevelHelpTips:String = "Resources/GameData/LevelHelpTips.xml";
        public static const OpenBoxConfig:String = "Resources/GameData/OpenItemBox.xml";
        public static const TranscriptInfo:String = "Resources/GameData/TRANSCRIPTINFOInfo.xml";
        public static const PrevEquipSwf:String = "Resources/Effect/PreEquip.swf";
        public static const Constellation:String = "Resources/GameData/constellationInfo.xml";
        public static const GameSkillAudio:String = "Resources/GameMusic/Skill/";
        public static const FilterDic:String = "Resources/Filter.swf?v=5";
        public static const StoryDisplayConfig:String = "Resources/GameData/StoryDisplayConfig.xml";
        public static const ActivityItems:String = "Resources/GameData/ActivityItems.xml";
        public static const RainEffectSwf:String = "Resources/Effect/RainEffect.swf";
        public static const GradeBibleConfig:String = "Resources/GameData/GradeBibleConfig.xml";
        public static const AnswerQuestion:String = "Resources/GameData/Question.xml";
        public static const EquipSetList:String = "Resources/GameData/CSETInfo.bml";
        public static const OpenBoxEffect:String = "Resources/Effect/OpenBoxEffect.swf";

        public static var ActivityCodePath:String = "http://yxwz.2918.com/huodongzhongxin/2011-10/57643.html";
        public static var GameSocketIP:String;
        public static var BBS:String = "http://cjpp.blueriver123.com/bbs/index.php";
        public static var CurrentServerId:int = 0;
        public static var GreenServicePhone:String = "";
        public static var GameSocketPort:uint;
        public static var EnemyVersion:String = "1.3";
        public static var GreenService:String = "Resources/GoldCustomer/GoldCustomer_51.swf";
        public static var LanguageModelPath:String = "";
        public static var LanguageModel:MovieClip = null;
        public static var PlayerVersion:String = "1.3";
        public static var GMUrl:String = "";
        public static var RankConfig:String = "Resources/GameData/Rank.xml";
        public static var GameDataFilePack:String = "Resources/GameData/data.gzp";
        public static var Env:String = "";
        public static var NPCVersion:String = "1.5";
        public static var ItemIconVersion:String = "1.1";
        public static var ActivitVersion:String = "1.0";
        public static var VerificationPath:String = "";
        public static var OfficialWebsite:String = "http://yxwz.2918.com/";
        public static var MusicVersion:String = "1.0";
        public static var GreenServiceMail:String = "";
        public static var GamePay:String = "http://192.168.7.50/login_hoho/pay/index.php";
        public static var AccSocketIP:String;
        public static var GameChengMi:int = 2;
        public static var GMNotice:String = "本地运行";
        public static var SkillVersion:String = "1.1";
        public static var LoginUrl:String = "http://192.168.7.50/login_hoho/main.php";
        public static var UILibrary:String = "Resources/UILibrary_1.swf?v=1+";
        public static var Freshman:String = null;
        public static var FaceVersion:String = "1.1";
        public static var LanguagePack:String = "Resources/language.txt?v=";
        public static var AccSocketPort:uint = 0;
        public static var ModuleLoadVerion:String = "";
        public static var ChatFaceVerion:String = "2.0";
        public static var EXurl:String = "";
        public static var GameSeverNum:uint;
        public static var OtherCountryFt:int;
        public static var CurrentServer:String = "0";
        public static var MountPressTime:int = 0;

    }
}//package 
